# .project metadata for WasmEdge Runtime
# Documentation: https://github.com/cncf/automation/tree/main/utilities/dot-project

schema_version: "1.0.0"
slug: "wasmedge"
name: "WasmEdge Runtime"
description: "WasmEdge is a lightweight, high-performance, and extensible WebAssembly runtime for cloud native, edge, and decentralized applications. It powers serverless apps, embedded functions, microservices, smart contracts, and IoT devices"
type: "project"
project_lead: "hydai"
slack_channels:
  - name: "#WasmEdge"
    primary: true

maturity_log:
  - phase: "sandbox"
    date: "2021-04-28T00:00:00Z"
    issue: "https://github.com/cncf/toc/pull/873"

repositories:
  - "https://github.com/WasmEdge/WasmEdge"

website: "https://wasmedge.org/"

artwork: "https://landscape.cncf.io/logos/wasmedge.svg"

adopters:
  path: "https://github.com/wasmedge/docs/blob/main/docs/contribute/users.md"


package_managers:
  docker: "WasmEdge/WasmEdge"
  fedora: "wasmedge"

social:
  twitter: "https://twitter.com/realwasmedge"

security:
  policy:
    path: "https://github.com/WasmEdge/WasmEdge/blob/master/SECURITY.md"
  contact:
    advisory_url: "https://github.com/WasmEdge/WasmEdge/security/advisories/new"

governance:
  contributing:
    path: "https://github.com/WasmEdge/WasmEdge/blob/master/docs/CONTRIBUTING.md"
  code_of_conduct:
    path: "https://github.com/WasmEdge/WasmEdge/blob/master/docs/CODE_OF_CONDUCT.md"
  contributor_ladder:
    path: "https://github.com/WasmEdge/WasmEdge/blob/master/docs/CONTRIBUTOR_LADDER.md"

legal:
  license:
    path: "https://github.com/WasmEdge/WasmEdge/blob/master/LICENSE"
  identity_type:
    has_dco: true
    has_cla: false
    dco_url:
      path: "https://developercertificate.org/"

documentation:
  readme:
    path: "https://github.com/WasmEdge/WasmEdge/blob/master/README.md"
  api:
    path: "https://wasmedge.org/docs/embed/c/reference/latest"

landscape:
  category: "Runtime"
  subcategory: "Container Runtime"

# CLOMonitor Score: 88/100
# Documentation: 100 | License: 100 | Best Practices: 68 | Security: 73
